// <auto-generated />
using System;
using ConsoleApp1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    partial class ECommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp1.models.Category", b =>
            {
                b.Property<int>("CategoryId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));
                b.Property<string>("CategoryName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("ImageUrl").HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.HasKey("CategoryId");
                b.ToTable("Categorys");
            });

            modelBuilder.Entity("ConsoleApp1.models.Order", b =>
            {
                b.Property<int>("OrderId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));
                b.Property<DateTime>("OrderDate").HasColumnType("datetime2");
                b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<decimal>("TotalAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("OrderId");
                b.HasIndex("UserId");
                b.ToTable("Orders");
            });

            modelBuilder.Entity("ConsoleApp1.models.OrderItem", b =>
            {
                b.Property<int>("OrderItemId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));
                b.Property<int>("OrderId").HasColumnType("int");
                b.Property<int>("ProductId").HasColumnType("int");
                b.Property<int>("Quantity").HasColumnType("int");
                b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,2)");
                b.HasKey("OrderItemId");
                b.HasIndex("OrderId");
                b.HasIndex("ProductId");
                b.ToTable("OrderItems");
            });

            modelBuilder.Entity("ConsoleApp1.models.Product", b =>
            {
                b.Property<int>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));
                b.Property<int>("CategoryId").HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<bool>("IsAvailable").HasColumnType("bit");
                b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<string>("ProductName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<int>("StockQuantity").HasColumnType("int");
                b.HasKey("ProductId");
                b.HasIndex("CategoryId");
                b.ToTable("Products");
            });

            modelBuilder.Entity("ConsoleApp1.models.Review", b =>
            {
                b.Property<int>("ReviewId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));
                b.Property<string>("Comment").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<int>("ProductId").HasColumnType("int");
                b.Property<int>("Rating").HasColumnType("int");
                b.Property<DateTime>("ReviewDate").HasColumnType("datetime2");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("ReviewId");
                b.HasIndex("ProductId");
                b.HasIndex("UserId");
                b.ToTable("Reviews");
            });

            modelBuilder.Entity("ConsoleApp1.models.User", b =>
            {
                b.Property<int>("UserId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<DateTime>("RegistrationDate").HasColumnType("datetime2");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("UserId");
                b.ToTable("Users");
            });

            // علاقات الـ Navigation (مدمجة لمنع التكرار)
            modelBuilder.Entity("ConsoleApp1.models.Category", b => { b.Navigation("Products"); });
            modelBuilder.Entity("ConsoleApp1.models.Order", b => { b.Navigation("OrderItems"); });
            modelBuilder.Entity("ConsoleApp1.models.Product", b => { b.Navigation("OrderItems"); b.Navigation("Reviews"); });
            modelBuilder.Entity("ConsoleApp1.models.User", b => { b.Navigation("Orders"); b.Navigation("Reviews"); });

#pragma warning restore 612, 618
        }
    }
}